### ISSUE TITLE
Having <title> change to course name 

### ISSUE THREAD

**Issue by kirkoplerno** [webhat/oplerno#139]
![screen shot 2015-01-09 at 2 46 50 pm](https://cloud.githubusercontent.com/assets/6529006/5686129/5f0aee3e-980e-11e4-9d89-43bb4d197057.png)

I think it'll help folks navigate from tabs and windows with a title reflecting the course on the page they're viewing.

**Comment by kirkoplerno** [comment]
I see now that it is, in fact, in the title.  What would you think about making it come up before "Oplerno"?

**Comment by webhat** [comment]
:+1:
