### ISSUE TITLE
Update to the 'Welcome' faculty email

### ISSUE THREAD

**Issue by kirkoplerno** [webhat/oplerno#149]
Hello and welcome Professor!
Thanks again for your interest in working with Oplerno. This email serves as somewhat of an orientation resource "packet." Below, you'll find links to our modules and to documents that will help you establish your courses within the Oplerno network. First, let's get started with your new email account.
Email Account and Instructions
*Access: email.oplerno.com*
Username:@oplerno.com
Password: lfkadsfjalewjfaweifjalkwef

**Comment by webhat** [comment]
Current mail: 
https://github.com/webhat/oplerno/blob/master/app/views/notification/faculty_invite.html.haml

**Comment by webhat** [comment]
Just checking @kirkoplerno you want to wipe out the rest of the email, or send a follow up?

**Comment by kirkoplerno** [comment]
No just add the line "Access: email.oplerno.com"

I think some recipients of the email dont know where to input the login info since we list it after the username and pw rather than before

**Comment by webhat** [comment]
Should be activated in :arrow_up: commit.
