### ISSUE TITLE
Congrats! email after someone uses a code

### ISSUE THREAD

**Issue by kirkoplerno** [webhat/oplerno#170]
Here is what the congrats! email should say:

SUBJECT: You're one step closer to $50 at Oplerno!

BODY:
Your friend *|NEW EMAIL ADDRESS THAT JUST SIGNED UP FOR AN ACCOUNT USING THE REFERRAL CODE|* just signed up for an account at Oplerno!

One of your friends has used an invitation you created to sign up for an account at Oplerno!

For you to receive your $50 toward an Oplerno course, your friend just has to enroll in a course and stay in the course for at least four weeks (we need to make sure your friend is serious about taking the course after all)!

You can build up as many $50 credits toward Oplerno courses as you would like.  Remember, they hold no cash value and can only be used toward Oplerno courses.

Kind regards,

The Team at Oplerno

**Comment by webhat** [comment]
Agree with everything, except revealing the email address of the person who signed up.

**Comment by kirkoplerno** [comment]
I can see that.  My thought was that they'd know the referrals but that's not the case for sure.  Should we just try it without the email address and see what happens?  People might get bombarded with these emails, but we can scale it back or add an unsubscribe?  We dont wanna get pinged as spam

**Comment by webhat** [comment]
One of the reasons we still use Mandrill for out transactional mail is that they keep track of these things.

**Comment by kirkoplerno** [comment]
'These things' meaning getting pinged as spam?

**Comment by webhat** [comment]
Among other things.

**Comment by webhat** [comment]
Next update
