### ISSUE TITLE
email that comes to the new, referred person edits

### ISSUE THREAD

**Issue by kirkoplerno** [webhat/oplerno#171]
Here is what the email that comes to the new, referred person should say:

SUBJECT:	
You have $50 to use toward an Oplerno course!

BODY:
Great news, you now have $50 to use in the Oplerno Marketplace!

Click here to enroll in a course and use your credit!  (Link to Marketplace) 

Kind regards,

The Team at Oplerno

**Comment by webhat** [comment]
I think there are too many exclamation marks. And you can't use the credits immediately so it's a little misleading.

I've changed it to:

----

Subject: You have $50 to use toward an Oplerno course!

## You have $50 credits

Great news, you now have $50 to use in the [Oplerno Marketplace!](https://enroll.oplerno.com/)

You will receive credits once the class has passed the time for a refund.

Kind regards,

The Team at Oplerno

**Comment by kirkoplerno** [comment]
The new person should be able to use the credits immediately, IMO.  I dont
see the function in making them wait.  This isnt a rebate system.

**Comment by webhat** [comment]
The issue is that it has been built as a rebate system, which means that if we tell them they can cash it in now and they can't we'd simply be lying.

**Comment by kirkoplerno** [comment]
An incentives program like this should provide an immediate discount to the
new user.  Without that, I can nearly guarantee that the conversion rate
plummets.  This could be the reason we arent converting people who are
putting courses into their carts but not paying.

**Comment by webhat** [comment]
This is your assumption, and not based in fact.

**Comment by kirkoplerno** [comment]
Is your assumption different?

**Comment by webhat** [comment]
Nope, I don't need to assume anything. The numbers in the admin panel show me nobody has used the invite credits besides you and I nobody has even looked at the credits. From Google Analytics I can see There were 13 unique pageviews and nobody besides you and I created and account.

https://enroll.oplerno.com/admin/invite_credits

**Comment by webhat** [comment]
And I of course 84% of visitors were in the US so they don't get credits anyway.
