### ISSUE TITLE
Email To Confirm New Account needs edits

### ISSUE THREAD

**Issue by kirkoplerno** [webhat/oplerno#172]
I dont understand from where this email derives?  I signed up with a @gmail.com and it gave me a localhost ID?  Why would it do that if I signed up with my own gmail address?

Hello ab25df8b702@localhost!  <-- why not just put the email address I entered here?

Welcome! You have signed up successfully.

You can confirm your account email through the link below:

Confirm my account

Link not working? Copy and paste the one below into your browser:

http://enroll.oplerno.com/users/confirmation?confirmation_token=8y4vAQsKzXNidXjYj-9L

Kind regards,

The Team at Oplerno

**Comment by webhat** [comment]
Fixed in next reload
