### ISSUE TITLE
Browse By Instructor cut off on left side of page

### ISSUE THREAD

**Issue by kirkoplerno** [webhat/oplerno#177]
![screen shot 2015-05-20 at 10 57 32 am](https://cloud.githubusercontent.com/assets/6529006/7729005/7c3ddbf4-fee0-11e4-9048-076647c75340.png)

**Comment by webhat** [comment]
I know the current site sucks. Do you want me to spend time fixing it or work on implementing the new design? If you want me to work on the new design you don't need to open any more bugs related to the old design as I will just close them.

And as this is all related to one issue, and one size you don't need to open anymore bugs related to this.

**Comment by kirkoplerno** [comment]
I'm just posting what I see.  Can you give us a timeline for new design?
Not trying to pour salt in wounds, just using the system we had set up and
I hadnt seen this bug before, so I posted it.
